window.WORD_BANK = {
  easy: [
    "access", "agent", "alarm", "alias",
    "alpha", "amber", "armor", "asset",
    "audit", "badge", "beacon", "black",
    "blade", "blind", "block", "breach",
    "brief", "burner", "cache", "cable",
    "cipher", "cloak", "clone", "cloud",
    "code", "covert", "crack", "crypt",
    "cyber", "daemon", "data", "decoy",
    "delta", "drone", "echo", "entry",
    "erase", "exfil", "false", "field",
    "flare", "forge", "ghost", "grid",
    "guard", "hack", "hash", "intel",
    "key pad", "laser", "leak", "link",
    "lock", "logic", "mask", "matrix",
    "node", "noise", "optic", "patch",
    "payload", "pixel", "proxy", "pulse",
    "radio", "relay", "route", "scan",
    "scope", "scrub", "secure", "shell",
    "signal", "silent", "siren", "snare",
    "spoof", "stealth", "switch", "trace",
    "track", "trojan", "tunnel", "vault",
    "vector", "virus", "watch", "wire",
    "zero", "backup", "binary", "buffer",
    "bypass", "camera", "carrier", "client",
    "cookie", "darknet", "device", "digital",
    "firewall", "gateway", "implant", "kernel",
    "key card", "lattice", "malware", "module",
    "packet", "scanner", "server", "socket",
    "target", "terminal", "uplink", "webcam",
    "wire tap", "air gap", "back door", "botnet",
    "dead drop", "decrypt", "encrypt", "exploit",
    "finger", "hot line", "insider", "intrude",
    "monitor", "override", "sandbox", "sleeper",
    "sniffer", "staging", "tracker", "trigger",
    "war room",
    "adaptor", "antenna", "backlog", "bandwidth",
    "bios", "bridge", "burst", "channel",
    "checksum", "chipset", "console", "contact",
    "control", "cortex", "cradle", "cursor",
    "decoder", "dialer", "dock", "driver",
    "emitter", "encoder", "firebreak", "frame",
    "handset", "hub", "inject", "jack",
    "jumper", "key ring", "key slot", "linkage",
    "memory", "modem", "optic feed", "probe",
    "reader", "record", "redact", "router",
    "scramble", "sector", "sensor", "socket key",
    "spectrum", "stack", "stream", "tap line",
    "uplink key", "watcher", "witness", "zero key",
    "code book", "cover name", "drop point", "field kit",
    "ghost key", "handoff", "lock box", "signal key",
    "trace line", "wire room"
  ],

  medium: [
    "adaptive", "airborne", "air gapped", "anonymity",
    "archive", "back channel", "back trace", "biometric",
    "black site", "blind spot", "blue print", "boot strap",
    "bread crumb", "broadcast", "burn notice", "circuitry",
    "clearance", "cloaking", "cold boot", "command",
    "compromise", "counter spy", "credentials", "cross link",
    "data bank", "dead letter", "dead drop", "debugger",
    "deep fake", "detector", "disguise", "dossier",
    "drone feed", "echelon", "endpoint", "exposure",
    "failover", "firewall", "firmware", "forensics",
    "frequency", "geofence", "ghost line", "handshake",
    "honeypot", "hot wire", "identity", "implant",
    "intercept", "intrusion", "keylogger", "keystone",
    "kill chain", "kill zone", "latchkey", "listener",
    "mainframe", "metadata", "microchip", "night watch",
    "obfuscate", "off grid", "operator", "passcode",
    "perimeter", "phishing", "protocol", "quarantine",
    "rat line", "redacted", "repeater", "resolver",
    "rootkit", "safe house", "scrambler", "semaphore",
    "shadow net", "signal jam", "silencer", "spoofing",
    "spy glass", "steganography", "surveillance", "tail gate",
    "tape worm", "telemetry", "tokenize", "tracker",
    "traffic", "transmit", "tripwire", "uplinked",
    "watch list", "wireless", "zeroize", "authentication",
    "authorization", "backscatter", "blackmail", "blackout",
    "burn phone", "camera feed", "certified", "checkpoint",
    "clandestine", "compartment", "counterhack", "courier",
    "cryptex", "dark fiber", "dark room", "datagram",
    "dead hand", "deception", "disavowal", "drop zone",
    "enclave", "encrypted", "facial scan", "failsafe",
    "fingerprint", "ghost write", "interlock", "key server",
    "lockdown", "malicious", "microdrone", "networked",
    "night vision", "opsec", "overwatch", "paranoia",
    "pass phrase", "postern", "privilege", "rendezvous",
    "reconnaissance", "red team", "scrubbed", "shadowing",
    "signal box", "surveillant", "switch board", "sysadmin",
    "tactical", "threat intel", "transponder", "under cover",
    "unlisted", "whitelist", "wire guard", "zero trust",
    "access point", "active scan", "alert state", "analog tap",
    "asset file", "back route", "black bag", "blind drop",
    "burn list", "cipher key", "clear signal", "code phrase",
    "control room", "covert entry", "cover story", "data shard",
    "dead channel", "drop site", "field agent", "field office",
    "ghost route", "hidden relay", "identity card", "inside source",
    "key phrase", "key vault", "link monitor", "listen post",
    "mission log", "network map", "night entry", "null route",
    "packet loss", "passive scan", "relay chain", "remote feed",
    "route map", "safe channel", "signal mask", "silent entry",
    "source file", "spectrum scan", "staging area", "tap point",
    "trace route", "transfer key", "watch floor", "wire room",
    "access log", "burn route", "cache wipe", "camera loop",
    "covert signal", "dark channel", "data courier", "device clone",
    "false route", "field handler", "ghost relay", "hidden service",
    "implant key", "network watch", "packet relay", "secure line",
    "signal relay", "silent channel", "source code", "target file",
    "trace filter", "watch post", "wire scan", "zero route"
  ],

  hard: [
    "access broker", "adversarial", "air gap jump", "anonymizer",
    "anti forensic", "back connect", "backscatter", "behavioral",
    "biometrics", "black archive", "black budget", "black channel",
    "black packet", "blind relay", "boot loader", "bread crumbing",
    "command node", "compartmented", "counter intel", "counter measure",
    "crypt analysis", "cryptogram", "data center", "data diode",
    "data poisoning", "dead man", "dead reckoning", "deconfliction",
    "decryption", "deniability", "disinformation", "disposable",
    "doppelganger", "drop server", "eavesdropper", "encryption",
    "exfiltration", "exploit kit", "fingerprinting", "forensic wipe",
    "geolocation", "ghost protocol", "hardening", "honey network",
    "identity forge", "infiltration", "intelligence", "interdiction",
    "key exchange", "key material", "key stream", "kill box",
    "lateral move", "malvertising", "micro camera", "misdirection",
    "multifactor", "night crawler", "nonattribution", "obfuscation",
    "operations", "packet capture", "pass phrase", "persistence",
    "pretexting", "privilege", "provisioning", "radio frequency",
    "reconnaissance", "remote shell", "root access", "safe cracker",
    "side channel", "sigint", "social engineer", "spearphishing",
    "surveillance", "switch craft", "telepresence", "threat model",
    "tradecraft", "traffic flow", "transmission", "untraceable",
    "vulnerability", "watch tower", "watermarking", "wiretapping",
    "access control", "adversary sim", "anomaly detect", "back door chain",
    "black ledger", "black transit", "bot controller", "cipher suite",
    "credentialing", "cryptographic", "dark network", "data breach",
    "dead station", "defense grid", "digital forensic", "domain fronting",
    "endpoint guard", "exploit broker", "false identity", "firmware hack",
    "ghost account", "hardware token", "interception", "intrusion set",
    "key rotation", "malware drop", "micro target", "network pivot",
    "packet filter", "pass key chain", "phantom route", "privileged",
    "recon flight", "remote access", "sandbox escape", "secure channel",
    "security clearance", "signal intercept", "sleeper cell", "spoof network",
    "supply chain", "surveillance grid", "threat actor", "traffic mirror",
    "transmission key", "underground", "underveillance", "watch station",
    "zero day",
    "access pattern", "active surveillance", "adversary profile", "air gap transfer",
    "asset handler", "behavior profile", "black bag operation", "blind transfer",
    "burn protocol", "camera corridor", "channel hopping", "cipher material",
    "covert access", "credential cache", "dead channel route", "digital dead drop",
    "disposable identity", "encrypted relay", "field surveillance", "frequency mask",
    "ghost infrastructure", "hardware beacon", "hidden partition", "identity package",
    "implant channel", "intercept buffer", "key compromise", "key recovery",
    "link analysis", "memory capture", "network sensor", "operational alias",
    "packet replay", "passive intercept", "physical access", "proxy infrastructure",
    "radio silence", "remote beacon", "route analysis", "secure transport",
    "signal masking", "silent service", "source handling", "spectrum monitor",
    "staging network", "surveillance route", "target package", "traffic capture",
    "transfer protocol", "trusted channel", "watch pattern", "wireless bridge",
    "zero trust policy", "access telemetry", "black site access", "covert collection",
    "credential vault", "dark fiber route", "deception channel", "endpoint compromise",
    "field encryption", "forensic buffer", "ghost service", "identity audit",
    "implant telemetry", "network concealment", "packet injection", "signal deception",
    "source compartment", "surveillance loop", "trace suppression", "wireless relay"
  ],

  expert: [
    "adversary infrastructure", "anti forensics", "asymmetric cryptography", "biometric spoofing",
    "clandestine operations", "command and control", "compartmentalization", "counter intelligence",
    "credential harvesting", "cryptographic protocol", "deanonymization", "deauthentication attack",
    "disinformation campaign", "electromagnetic surveillance", "exfiltration channel", "exploit development",
    "fingerprint analysis", "intrusion detection", "key management", "malware analysis",
    "micro electronics", "network segmentation", "non repudiation", "operational security",
    "packet inspection", "penetration testing", "privilege escalation", "radio triangulation",
    "reverse engineering", "security architecture", "signal intelligence", "social engineering",
    "spear phishing", "steganographic channel", "surveillance camera", "threat intelligence",
    "traffic analysis", "transmission security", "vulnerability research", "wireless triangulation",
    "zero knowledge proof", "access persistence", "advanced persistent threat", "air gapped network",
    "behavioral analysis", "black site protocol", "browser exploitation", "clandestine channel",
    "communications relay", "counter intrusion", "credential stuffing", "cryptographic key",
    "deception operation", "digital espionage", "disavowable asset", "electronic warfare",
    "endpoint telemetry", "exfiltration route", "exploit framework", "facial recognition",
    "firmware implant", "forensic artifact", "identity correlation", "intelligence cycle",
    "intercept station", "key escrow", "lateral movement", "malicious payload",
    "metadata analysis", "network enumeration", "operational cover", "packet forensics",
    "passive collection", "persistent access", "remote exploitation", "secure compartment",
    "side channel attack", "signal collection", "source protection", "supply chain attack",
    "surveillance platform", "threat assessment", "traffic correlation", "transmission burst",
    "undercover asset", "vulnerability chain", "wireless implant", "zero trust architecture",
    "access control matrix", "active directory abuse", "air gap bypass", "anomaly detection",
    "attack surface mapping", "behavioral telemetry", "certificate pinning", "covert communications",
    "credential replay", "cross domain access", "data loss prevention", "digital signature",
    "endpoint detection", "encrypted tunnel", "forensic acquisition", "identity federation",
    "implant delivery", "intelligence liaison", "memory forensics", "network discovery",
    "passive reconnaissance", "privileged account", "protocol analysis", "remote access tunnel",
    "secure enclave", "session hijacking", "signal interception", "source validation",
    "threat hunting", "traffic inspection", "trusted execution", "wireless reconnaissance",
    "access behavior analysis", "active signal collection", "adversary emulation", "air gap transfer protocol",
    "anomaly correlation", "asset validation protocol", "behavioral fingerprint", "black site communications",
    "clandestine access route", "covert infrastructure", "credential compromise", "cross domain collection",
    "data exfiltration path", "deception infrastructure", "digital surveillance", "electronic interception",
    "endpoint compromise chain", "forensic timeline analysis", "frequency hopping pattern", "hardware surveillance",
    "identity deception plan", "implant command channel", "intelligence collection", "key compromise recovery",
    "lateral access path", "metadata correlation", "network concealment", "network traffic baseline",
    "operational compartment", "packet timing analysis", "passive signal collection", "persistent foothold",
    "physical surveillance", "radio frequency analysis", "remote implant channel", "route correlation",
    "secure transfer protocol", "signal attribution", "signal masking pattern", "source authentication",
    "spectrum monitoring", "surveillance detection route", "traffic pattern analysis", "trusted access path",
    "wireless collection node", "access token replay", "behavioral anomaly model", "clandestine relay network",
    "covert data channel", "credential exposure path", "encrypted command path", "endpoint surveillance",
    "forensic memory capture", "identity verification chain", "implant persistence", "network access broker",
    "operational deception", "packet capture analysis", "privileged access path", "remote collection point",
    "signal interception route", "source compartmentation", "surveillance infrastructure", "threat actor profile"
  ],

  elite: [
    "confirm the relay before entry",
    "burn the key after use",
    "hold traffic until the window opens",
    "route the packet through backup",
    "verify the source before contact",
    "clear the cache before extraction",
    "move the asset before dawn",
    "switch channels after the burst",
    "watch the east entrance",
    "leave no logs on exit",
    "use the alternate service route",
    "confirm the beacon is clean",
    "drop the package after midnight",
    "abort if the watcher returns",
    "keep the source off network",
    "mirror traffic from the relay",
    "wipe memory before disconnect",
    "hold position until the signal",
    "move only after confirmation",
    "rotate credentials after access",
    "keep the channel compartmented",
    "break contact at first warning",
    "use passive collection only",
    "change routes before the meet",
    "burn the alias after extraction",
    "scan the room before entry",
    "confirm the courier at distance",
    "avoid the primary gateway",
    "stage access through the proxy",
    "close the tunnel after transfer",
    "move the archive to cold storage",
    "keep the implant off telemetry",
    "watch for repeated surveillance",
    "hold the burst until clear",
    "verify the dead drop first",
    "route collection through the relay",
    "isolate the host before analysis",
    "clear the terminal after use",
    "leave the decoy credentials active",
    "recover the token without changes",
    "observe before making contact",
    "keep the package out of sight",
    "switch to backup communications",
    "confirm the perimeter is quiet",
    "drop access after the window",
    "avoid contact near the station",
    "verify the room is screened",
    "move the source to fallback",
    "keep command traffic low",
    "burn the relay if queried",
    "pause collection during patrol",
    "use the maintenance account once",
    "rotate the proxy after transfer",
    "verify both ends of channel",
    "hold the asset at safe house",
    "change frequency after each burst",
    "keep metadata outside the archive",
    "check the route for tails",
    "cut telemetry before entry",
    "stage the payload offline",
    "verify the image before analysis",
    "move through service access",
    "keep the source name separate",
    "watch the checkpoint from distance",
    "hold the key until needed",
    "disable remote management first",
    "confirm the target before action",
    "route around the monitored subnet",
    "use the decoy only once",
    "verify the clock before timeline",
    "keep extraction paths separate",
    "hold transmission during the sweep",
    "move only under normal traffic",
    "leave the original drive untouched",
    "confirm no unknown transmitters",
    "rotate the channel after contact",
    "keep the courier compartmented",
    "break the session after transfer",
    "watch the access logs closely",
    "delay the callback until clear",
    "keep the device in shielded storage",
    "confirm the badge before entry",
    "switch routes after the checkpoint",
    "move the drive before shift change",
    "keep surveillance outside the meet",
    "verify the listener has cleared",
    "use the quiet service entrance",
    "confirm the packet source first",
    "move the relay before sunrise",
    "keep the operation on need basis",
    "wipe temporary keys on exit",
    "avoid repeated travel patterns",
    "confirm the fallback site is clean",
    "route the archive through staging",
    "keep the decoy believable",
    "verify the implant stayed dormant",
    "watch the camera cycle twice",
    "keep the meeting under five minutes",
    "confirm the endpoint before login",
    "use the alternate rendezvous point",
    "rotate the burner after contact",
    "leave the package untouched",
    "verify the service account first",
    "cut the link if traced",
    "keep the watcher outside range",
    "move the payload under cover",
    "confirm the handoff before leaving",
    "hold the extraction route open",
    "switch to cold storage",
    "keep the false trail simple",
    "verify the credential path",
    "use the backup relay now",
    "move before the next patrol",
    "burn the token after commit",
    "confirm the source identity again",
    "keep the subnet quiet",
    "route the signal through cover",
    "watch the western service door",
    "hold until the spectrum clears",
    "clear the staging host",
    "keep the archive encrypted",
    "verify the transport is clean",
    "move through the north corridor",
    "switch to the reserve channel",
    "keep the trace below threshold",
    "confirm no tail at exit",
    "use the side entrance",
    "burn the temporary access key",
    "hold the line until transfer",
    "verify the relay clock",
    "keep the source isolated",
    "move the package after dark",
    "route through the trusted proxy",
    "watch for duplicate credentials",
    "clear the handoff point",
    "confirm the backup route",
    "keep the terminal offline",
    "use the screened room only",
    "move after the camera reset",
    "hold the burst for ten seconds",
    "verify the monitor is blind",
    "keep access short and quiet",
    "watch for unusual polling",
    "clear the local history",
    "confirm the asset is ready",
    "move the archive in fragments",
    "keep the beacon powered down",
    "switch the implant to passive",
    "hold until the watcher passes",
    "verify the door sensor state",
    "use the fallback credential",
    "burn the session key now",
    "keep the relay one hop away",
    "move the source without notice",
    "confirm the staging node is clean",
    "watch the loading dock",
    "hold contact until tomorrow",
    "verify the drop site first",
    "keep the route unpredictable",
    "switch the uplink after commit",
    "move before logs rotate",
    "clear the capture buffer",
    "keep the false identity consistent",
    "use only the approved channel",
    "hold the archive offsite",
    "verify the secondary exit",
    "move the courier separately",
    "burn the old challenge phrase",
    "keep the transfer below threshold",
    "watch the lobby camera loop",
    "confirm the proxy is stable",
    "route the signal through noise",
    "hold the package until cleared",
    "keep the meeting off schedule",
    "verify no active collection nearby",
    "hold the channel",
    "switch to dark route",
    "confirm clean entry",
    "burn the access key",
    "watch the north gate",
    "move after the sweep",
    "keep the relay cold",
    "drop the false route",
    "verify the second exit",
    "hold until signal clears",
    "move through service hall",
    "keep the source quiet",
    "clear the active cache",
    "watch the camera loop",
    "route through cold link",
    "burn the cover name",
    "confirm the drop point",
    "hold outside sensor range",
    "switch to backup route",
    "keep the beacon dark",
    "move before shift change",
    "verify the safe channel",
    "watch the loading bay",
    "drop traffic at relay",
    "keep the implant silent",
    "clear the local buffer",
    "hold for second contact",
    "move after light change",
    "confirm the packet path",
    "watch the service door",
    "burn the field alias",
    "keep the wire clean",
    "route through ghost node",
    "verify the access log",
    "hold until patrol turns",
    "move below camera line",
    "switch the signal mask",
    "keep the tunnel closed",
    "confirm the blind spot",
    "watch for second tail",
    "burn the session token",
    "hold the target feed",
    "move through east stair",
    "keep the archive sealed",
    "route around watch post",
    "verify the relay chain",
    "drop the active link",
    "watch the west corridor",
    "hold before final entry",
    "move the source tonight",
    "keep the channel narrow",
    "confirm the route map",
    "burn the transfer key",
    "watch for signal drift",
    "hold at the safe house",
    "move under normal traffic",
    "keep the proxy quiet",
    "verify the source file",
    "drop the trace route",
    "watch the outer gate",
    "hold until the scan ends",
    "move through lower access",
    "keep the target unaware",
    "confirm the hidden relay",
    "burn the old pass phrase",
    "watch the relay status",
    "hold the packet burst",
    "move the archive offsite",
    "keep the uplink brief",
    "verify the camera gap",
    "drop the decoy packet",
    "watch the side entrance",
    "hold until channel opens",
    "move before logs sync",
    "keep the contact isolated",
    "confirm the access point",
    "burn the temporary alias",
    "watch the signal floor",
    "hold the service key",
    "move through blind zone",
    "keep the transfer small",
    "verify the outbound path",
    "drop the false beacon",
    "watch for route changes",
    "hold near the second gate",
    "move after the relay burst",
    "keep the target offline",
    "confirm the clean handoff",
    "burn the fallback key",
    "watch the spectrum shift",
    "hold until traffic peaks",
    "move the drive at dusk",
    "keep the source offsite",
    "verify the cold archive",
    "drop the monitored route",
    "watch the lower corridor",
    "hold outside the subnet",
    "move after the trace falls",
    "keep the relay unlisted",
    "confirm the secure line",
    "burn the backup token",
    "watch the eastern camera",
    "hold the staging node",
    "move through dark fiber",
    "keep the cover simple",
    "verify the next relay",
    "drop the mirror traffic",
    "watch the route twice",
    "hold until lights cycle",
    "move the package alone",
    "keep the buffer offline",
    "confirm the source code",
    "burn the old route map",
    "watch the access pattern",
    "hold below trace level",
    "move through utility hall",
    "keep the signal masked",
    "verify the dead channel",
    "drop the active session",
    "watch for repeat scans"
  ]

};